### ISSUE TITLE
Connecting via REST before socket.io

### ISSUE THREAD

**Issue by BenEmdon** [Hacker-Chatroom/Hacker-Chatroom-Server#1]
So the whole reason why we made get rooms a REST endpoint was so we could choose to join a room prior to connecting. Should we still do this? Or rather should we have a 'rooms' socket event that returns the rooms when asked?

What are your guy's thoughts?

**Comment by JackyChiu** [comment]
The REST endpoint makes sense to do, from my understanding this is the flow we want.
- Run the client
- Enter Username
- Get what rooms are available
- Enter room you want to join
- Join the room
- Ready to chat!

**Comment by JackyChiu** [comment]
Let me know if this is what we want ^

**Comment by BenEmdon** [comment]
@VikramBombhi @kirinrastogi @Tuanhao Are you guys good with this?

**Comment by JackyChiu** [comment]
Is this good to close? Our current implementation follows the flow that I mentioned above
