### ISSUE TITLE
Rooms formats

### ISSUE THREAD

**Issue by JackyChiu** [Hacker-Chatroom/Hacker-Chatroom-Server#6]
## Suggestion
I was thinking we should pick a format for our rooms to be named. This way we don't get repetitive rooms, like `programming` and `PROgrammING`. 

## Example
Slack lets you only create rooms in lowercase, I like this approach, what do you guys think?

**Comment by vikrambombhi** [comment]
Yea I like that to, we could say only lowercase letters to be more strict

**Comment by JackyChiu** [comment]
And automatically take the input in as lowercase

**Comment by BenEmdon** [comment]
Sounds good to me 👍

**Comment by kirinrastogi** [comment]
Do we want to add hyphens in case of multiple words in a name?

**Comment by JackyChiu** [comment]
yeah that sounds good ^
